name: Deploy to GitHub Pages


on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [20.x]


    steps:
      - name: Get Files
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn run build

      - name: Add .nojekyll file
        run: touch ./.next/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .next
