name: Deploy to GitHub Pages


on:
  push:
    branches: [master]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      #- name: Set up pnpm
        #uses: pnpm/action-setup@v3
        #with:
          #version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install
          pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Add .nojekyll file
        run: touch ./.dist/.nojekyll

      #- name: Deploy
        #uses: JamesIves/github-pages-deploy-action@v4
        #with:
          #branch: gh-pages
          #folder: .vercel/output

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./dist
        #uses:
        #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./dist
